### PR TITLE
update to version 7 of storybook

### PR DESCRIPTION
**Pull request by willyboy**
A simpler version of the existing PR to upgrade to 7 that hopefully passes all checks. https://github.com/storybookjs/addon-queryparams/issues/5

### CODE REVIEW

**Comment by arthurdenner** [comment]
Hi, thanks for opening another proposal for a fix. I've been waiting for a fix for months too but the package seems rather unmaintained. Do you think you could publish your changes as another package on NPM?

**Review by felipeplets — APPROVED** [review]
LGTM

**Comment by felipeplets** [comment]
@shilman is there any concern or pending action to review this PR that I can help with?

**Comment by yannbf** [comment]
Hey everyone! So sorry this took so long. I'll be closing this PR as its work is superseded by #8.

**Pull request closed without merging**
